CREATE TABLE ROL(
    id INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IMG(
    id INTEGER PRIMARY KEY,
    url_img VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE USUARIO(
    id INTEGER PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    id_img INTEGER,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    nit VARCHAR(10) NOT NULL,
    estado VARCHAR(25) CHECK (estado IN ('Inactivo', 'Activo')) DEFAULT 'Activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_rol) REFERENCES ROL(id),
    FOREIGN KEY (id_img) REFERENCES IMG(id)
)

CREATE TABLE TARJETA(
    id INTEGER PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    numero VARCHAR(12) NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    codigo_seguridad VARCHAR(3) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES USUARIO(id)
)

CREATE TABLE PLAN(
    id INTEGER PRIMARY KEY,
    nombre VARCHAR(30) CHECK (nombre IN ('Mensual', 'Bimestral', 'Anual')) DEFAULT 'Mensual',
    precio INTEGER NOT NULL,
    nivel VARCHAR(30) CHECK (nivel IN ('Basico', 'Pro', 'Premium')) DEFAULT 'Basico',
    descripcion VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE SUSCRIPCION(
    id INTEGER PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_plan INTEGER NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR(25) CHECK( estado IN ('VENCIDO', 'ACTIVO')) DEFAULT 'ACTIVO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES USUARIO(id),
    FOREIGN KEY (id_plan) REFERENCES PLAN(id)
)

CREATE TABLE CATEGORIA_CONTENIDO(
    id INTEGER PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE CONTENIDO(
    id INTEGER PRIMARY KEY,
    id_categoria INTEGER NOT NULL,
    titulo VARCHAR(50) NOT NULL,
    anio_creacion DATE NOT NULL,
    sinopsis VARCHAR(250) NOT NULL,
    link_video VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA_CONTENIDO(id)
)

CREATE TABLE BITACORA_REPRODUCCION(
    id INTEGER PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_contenido INTEGER NOT NULL,
    fecha_reproduccion DATE NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIO (id),
    FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id)
)