version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: streaming_ayd
    restart: always
    environment:  
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mystreamingapp
    ports:      
      - "5432:5432"
    volumes:    
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: